version: "3.1"
services:
  db_service:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: discord
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - db
  bot:
    build: ./src
    container_name: bot
    networks:
      - db

    volumes:
      - ./src/:/app
    depends_on:
      - db_service

volumes:
  db:
  app:
networks:
  db:
